export const GET_STATE = 'GET_STATE'
export const GET_HOT_PUBLICATIONS = 'GET_HOT_PUBLICATIONS'
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES'
export const SET_ACTIVE_ARTICLE = 'SET_ACTIVE_ARTICLE'
